const items = [
    {
        id: '001',
        image: 'images1/realme.webp',
        item_name: 'realme 12 Pro 5G (Navigator biege, 256 GB)',
        original_price: 31999 ,
        current_price:20999,
        discount_percentage: 34,
        return_period: 14,
        delivery_date: '15 Jan 2024',
        rating: {
            stars: 4.4,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images1/realmev60.webp',
        item_name: 'realme V 60 5G (Navigator biege, 256 GB)',
        original_price: 25000 ,
        current_price:17999,
        discount_percentage: 33,
        return_period: 14,
        delivery_date: '15 Jan 2024',
        rating: {
            stars: 4.4,
            count: 1400,
        },
    },
    {
        id: '003',
        image: 'images1/moto.jpg',       
        item_name: 'Motorola g85 5g (Sky blue, 128 GB)',
        original_price: 15999,
        current_price: 14400,
        discount_percentage: 10,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images1/samsung.jpg',
        item_name: 'Samsung galaxy s24 plus(grey, 256 GB)',
        original_price: 49000,
        current_price: 39999,
        discount_percentage: 20,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images1/vivo.jpg',
        item_name: 'Vivo V23 Pro (Sunligth White, 128 GB)',
        original_price: 29999,
        current_price: 24999,
        discount_percentage: 15,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
     },
    // {
    //     id: '006',
    //     image: 'images1/6f.jpg',
    //     company: 'Nike',
    //     item_name: 'Men ReactX Running Shoes',
    //     original_price: 14995,
    //     current_price: 14995,
    //     discount_percentage: 0,
    //     return_period: 14,
    //     delivery_date: '10 Oct 2023',
    //     rating: {
    //         stars: 0.0,
    //         count: 0,
    //     },
    // },
    // {
    //     id: '007',
    //     image: 'images1/7f.jpg',
    //     company: 'The Indian Garage Co',
    //     item_name: 'Men Slim Fit Regular Shorts',
    //     original_price: 1599,
    //     current_price: 639,
    //     discount_percentage: 60,
    //     rating: {
    //         stars: 4.2,
    //         count: 388,
    //     },
    // },
    // {
    //     id: '008',
    //     image: 'images1/8f.jpg',
    //     company: 'Nivea',
    //     item_name: 'Men Fresh Deodrant 150ml',
    //     original_price: 285,
    //     current_price: 142,
    //     discount_percentage: 50,
    //     return_period: 14,
    //     delivery_date: '10 Oct 2023',
    //     rating: {
    //         stars: 4.2,
    //         count: 5200,
    //     },
    // }
];
